# Generated by Django 3.0.3 on 2020-04-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelterInformation',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='pk')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='보호소이름')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='보호소 위치')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='보호소 전화번호')),
                ('area', models.CharField(blank=True, max_length=300, null=True)),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='위도')),
                ('lng', models.FloatField(blank=True, null=True, verbose_name='경도')),
            ],
        ),
    ]
