# Generated by Django 3.0.3 on 2020-02-29 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=150, verbose_name='댓글'),
        ),
        migrations.AlterField(
            model_name='post',
            name='feature',
            field=models.CharField(max_length=200, verbose_name='특징'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='이미지'),
        ),
        migrations.AlterField(
            model_name='post',
            name='miss_date',
            field=models.DateTimeField(verbose_name='실종 날짜'),
        ),
        migrations.AlterField(
            model_name='post',
            name='miss_loc',
            field=models.CharField(max_length=100, verbose_name='실종 위치'),
        ),
        migrations.AlterField(
            model_name='post',
            name='species',
            field=models.CharField(max_length=30, verbose_name='품종'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=20, verbose_name='비밀번호'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='연락처'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=10, unique=True, verbose_name='아이디'),
        ),
    ]
